### PR TITLE
Refactored and fixed override approach

### PR DESCRIPTION
**Pull request by Rarst**
1. Did away with ancient `create_function()` stuff.
2. Changed `null` overrides on transients into proper object:
  - fixes error notices on trying to list updates
  - fixes error notice on checking for version match
  - prevents update HTTP request being forced by time mismatch

### CODE REVIEW

**Comment by Rarst** [comment]
It's been a while. :)

**Comment by johnbillion** [comment]
@Rarst Do you want to take over this plugin? I don't have any need or desire to maintain it these days. If so, I'll add you to the repo on w.org.

**Comment by Rarst** [comment]
Nope. :)

**Comment by Rarst** [comment]
I had folded this core update block implementation into my [Update Blocker](https://github.com/Rarst/update-blocker).

**Pull request closed without merging**
